_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 49
                - 51
                - 53
                - 55
                - 106
            "2":
                - 1
                - 5
                - 49
                - 51
                - 53
                - 55
                - 106
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
adam_epsilon:
    value: 1e-08
epochs:
    value: 20
hidden_dim:
    value: 4096
input_dim:
    value: 1800
learning_rate:
    value: 0.0001
output_dim:
    value: 5
train_batch_size:
    value: 256
valid_batch_size:
    value: 256
weight_decay:
    value: 0
